stages:
  train:
    cmd: ..\.venv\Scripts\python.exe -m src.training.train
    deps:
      - src
      - data/raw/bitext-limpio.parquet
    params:
      - data
      - training
      - artifacts
    outs:
      - models/modelo_idf.joblib
      - models/model_metadata.json
    metrics:
      - dvclive/metrics.json:
          cache: false
